<?php

/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

$dictionary['mv_SrvReq'] = array(
    'table' => 'mv_srvreq',
    'audited' => true,
    'activity_enabled' => false,
    'duplicate_merge' => true,
    'fields' => array(
        'description' => array(
            'name' => 'description',
            'vname' => 'LBL_DESCRIPTION',
            'type' => 'text',
            'comment' => 'Full text of the note',
            'full_text_search' => array(
                'enabled' => true,
                'boost' => '0.5',
                'searchable' => true,
            ),
            'rows' => '6',
            'cols' => '80',
            'duplicate_on_record_copy' => 'always',
            'required' => false,
            'massupdate' => false,
            'no_default' => false,
            'comments' => 'Full text of the note',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '1',
            'audited' => false,
            'reportable' => true,
            'unified_search' => true,
            'merge_filter' => 'disabled',
            'default' => '',
            'calculated' => false,
            'size' => '20',
            'studio' => 'visible',
        ),
        'root_cause' => array(
            'required' => false,
            'name' => 'root_cause',
            'vname' => 'LBL_ROOT_CAUSE',
            'type' => 'enum',
            'massupdate' => true,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '1',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 100,
            'size' => '20',
            'options' => 'root_cause_list',
            'default' => 'Installation Error',
            'dependency' => false,
        ),
        'category' => array(
            'required' => false,
            'name' => 'category',
            'vname' => 'LBL_CATEGORY',
            'type' => 'multienum',
            'isMultiSelect' => true,
            'massupdate' => true,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '1',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 100,
            'size' => '20',
            'options' => 'service_category_list',
            'default' => 'Appliances',
            'dependency' => false,
        ),
        'status' => array(
            'required' => false,
            'name' => 'status',
            'vname' => 'LBL_STATUS',
            'type' => 'enum',
            'massupdate' => true,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => '1',
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 100,
            'size' => '20',
            'options' => 'service_status_list',
            'default' => 'Open',
            'dependency' => false,
        ),
        'responsible_party' => array(
            'labelValue' => 'Responsible Party',
            'dependency' => '',
            'required' => false,
            'source' => 'non-db',
            'name' => 'responsible_party',
            'vname' => 'LBL_RESPONSIBLE_PARTY',
            'type' => 'relate',
            'massupdate' => false,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => 1,
            'audited' => false,
            'reportable' => true,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 255,
            'size' => '20',
            'id_name' => 'account_id',
            'module' => 'Accounts',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),
        'account_id' => array(
            'required' => false,
            'name' => 'account_id',
            'vname' => 'LBL_RESPONSIBLE_PARTY_ACCOUNT_ID',
            'type' => 'id',
            'massupdate' => false,
            'no_default' => false,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'enabled',
            'duplicate_merge_dom_value' => 1,
            'audited' => false,
            'reportable' => false,
            'unified_search' => false,
            'merge_filter' => 'disabled',
            'calculated' => false,
            'len' => 36,
            'size' => '20',
        ),
    ),
    'relationships' => array(
    ),
    'optimistic_locking' => true,
    'unified_search' => true,
    'full_text_search' => true,
);

if ( ! class_exists('VardefManager')) {
}
VardefManager::createVardef('mv_SrvReq', 'mv_SrvReq', array('basic', 'team_security', 'assignable', 'taggable'));
