<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/Resources/Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */
/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN m_CAMS
 */


class m_CAMS_sugar extends Basic {
    public $new_schema = true;
    public $module_dir = 'm_CAMS';
    public $object_name = 'm_CAMS';
    public $table_name = 'm_cams';
    public $importable = true;
    public $team_id;
    public $team_set_id;
    public $acl_team_set_id;
    public $team_count;
    public $team_name;
    public $acl_team_names;
    public $team_link;
    public $team_count_link;
    public $teams;
    public $assigned_user_id;
    public $assigned_user_name;
    public $assigned_user_link;
    public $tag;
    public $tag_link;
    public $id;
    public $name;
    public $date_entered;
    public $date_modified;
    public $modified_user_id;
    public $modified_by_name;
    public $created_by;
    public $created_by_name;
    public $description;
    public $deleted;
    public $created_by_link;
    public $modified_user_link;
    public $activities;
    public $following;
    public $following_link;
    public $my_favorite;
    public $favorite_link;
    public $locked_fields;
    public $locked_fields_link;
    public $last_activity_time;
    public $const_finish_date;
    public $opportunity_id_c;
    public $opportunity;
    public $pending_date;
    public $closing_date;
    public $sales_stage;
    public $square_footage;
    public $job_number;
    public $loan_max;
    public $currency_id;
    public $base_rate;
    public $loan_balance_current;
    public $cost_variance_budget;
    public $actual_lot_cost;
    public $actual_hard_costs;
    public $lot_cost_percent;
    public $hard_cost_per_sales;
    public $total_build_days;
    public $load_balance_remaining;
    public $contract_price;
    public $lender;
    public $superintendent;
    public $loan_number;
    public $projected_start_date;
    public $loan_status;
    public $construction_stage;
    public $floor_plan;
    public $community;
    public $sale_type;
    public $permit_status_note;
    public $permit_issued_date;
    public $permit_upload_date;
    public $books_closed;
    public $loan_comment;
    public $permit_total_days;
    public $permit_number;
    public $construction_note;
    public $garage_type;
    public $elevation;
    public $loan_maturity_date;
    public $opportunity_id1_c;
    public $lot_purchase_opportunity;
    public $lot_inventory_note;
    public $budget_created;
    public $spec_dom;
    public $actual_hard_lot_costs;
    public $warranty_exp;
    public $permits_paid_date;
    public $load_closed_date;
    public $gross_margin;
    public $projected_close_date;
    public $job_cost_margin_notes;
    public $mgr_walk_close_days;
    public $phase;
    public $lot_purchase_addendum;
    public $gcpf;
    public $estimate_errors;
    public $price_per_foot;
    
    public function bean_implements($interface){
        switch($interface){
            case 'ACL': return true;
        }
        return false;
    }
    
}
