<?php
/* File autogenerated by SugarCRM in ActivitesRelationship.php / buildSidecarDashletMeta */

$coreDefs = MetaDataFiles::loadSingleClientMetadata('view','attachments');
$coreDefs['dashlets'][0]['filter']['module'] = array('m_CAMS');
$coreDefs['dashlets'][0]['config']['link'] = 'm_cams_activities_1_notes';
$coreDefs['dashlets'][0]['preview']['link'] = 'm_cams_activities_1_notes';
$viewdefs['m_CAMS']['base']['view']['attachments'] = $coreDefs;
