<?php
/* File autogenerated by SugarCRM in ActivitesRelationship.php / buildSidecarDashletMeta */

$coreDefs = MetaDataFiles::loadSingleClientMetadata('view','active-tasks');
$coreDefs['dashlets'][0]['filter']['module'] = array('m_CAMS');
$coreDefs['custom_toolbar']['buttons'][0]['buttons'][0]['params']['link'] = 'm_cams_activities_1_tasks';
$coreDefs['tabs'][0]['link'] = 'm_cams_activities_1_tasks';
$coreDefs['tabs'][1]['link'] = 'm_cams_activities_1_tasks';
$viewdefs['m_CAMS']['base']['view']['active-tasks'] = $coreDefs;
