<?php
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

$dictionary['RT_DocuSign'] = array(
	'table'=>'rt_docusign',
	'audited'=>true,
		'duplicate_merge'=>true,
		'fields'=>array (
  'docusign_username' => 
  array (
    'name' => 'docusign_username',
    'vname' => 'LBL_RT_DOCUSIGN_USERNAME',
    'type' => 'varchar',
	'required' => false,
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => false,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => '255',
    'size' => '30',
  ), 
  'docusign_password' => 
  array (
    'name' => 'docusign_password',
	'required' => false,
    'vname' => 'LBL_RT_DOCUSIGN_PASSWORD',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => false,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => '255',
    'size' => '30',
  ),
  'docusign_integrationkey' => 
  array (
    'name' => 'docusign_integrationkey',
    'vname' => 'LBL_RT_DOCUSIGN_INTEGRATION_KEY',
    'type' => 'varchar',
	'required' => false,
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => false,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => '255',
    'size' => '36',
  ),
  'docusign_accountid' => 
  array (
    'name' => 'docusign_accountid',
    'vname' => 'LBL_RT_DOCUSIGN_ACCOUNTID',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
	'required' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => false,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => '255',
    'size' => '36',
  ),
  'docusign_connection_envoirnment' => 
  array (    
    'name' => 'docusign_connection_envoirnment',
    'vname' => 'LBL_RT_DOCUSIGN_CONNECTION_ENVIRONMENT',
    'type' => 'varchar',
	'required' => false,
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => false,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => '255',
    'size' => '25',
  ),  
  'docusign_base_url' => 
  array (
    'required' => false,
    'name' => 'docusign_base_url',
    'vname' => 'LBL_DOCUSIGN_BASE_URL',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => false,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => '255',
    'size' => '30',
  ),
  'docusign_notification_url' => 
  array (
    'required' => false,
    'name' => 'docusign_notification_url',
    'vname' => 'LBL_DOCUSIGN_NOTIFICATION_URL',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => false,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => '255',
    'size' => '30',
  ),
  'docusign_sugar_licence_key' => 
  array (
    'required' => false,
    'name' => 'docusign_sugar_licence_key',
    'vname' => 'LBL_RT_DOCUSGIN_SUGAR_LICENCE_KEY',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => false,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => '255',
    'size' => '30',
  ),
  'docusign_sugar_crm_userid' => 
  array (
    'required' => false,
    'name' => 'docusign_sugar_crm_userid',
    'vname' => 'LBL_RT_DOCUSIGN_SUGAR_CRM_USERID',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => false,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => '255',
    'size' => '30',
  ),
  'docusign_authentication_type' => 
  array (
    'required' => false,
    'name' => 'docusign_authentication_type',
    'vname' => 'LBL_RT_DOCUSIGN_USER_AUTHENTICATION_TYPE',
    'type' => 'varchar',
    'massupdate' => 0,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => false,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => '255',
    'size' => '30',
  ),
),
	'relationships'=>array (
),
	'optimistic_locking'=>true,
		'unified_search'=>true,
	);
if (!class_exists('VardefManager')){
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('RT_DocuSign','RT_DocuSign', array('basic','team_security','assignable'));
